### ISSUE TITLE
[BUG] importing `lyncs_io` raises `AttributeError` in python 3.8.

### ISSUE THREAD

**Issue by jadot-bp** [Lyncs-API/lyncs.io#27]
**Describe the bug**

>`import lyncs_io` in python 3.8+ yields the error
>
>`AttributeError: module 'importlib' has no attribute 'util'`
>
>Editing the problem file (`lyncs_utils/extensions.py`) such that `importlib.utils` is imported instead fixes this problem.

**To Reproduce**
If applicable, list the steps to reproduce the behavior:

> This can be reproduced by simply importing `lyncs_io` using a fresh environment in python 3.8.

**Error message / Output**
If applicable, paste here the error messages / output you get.

> Error(s) listed below:

<details>
  <summary>Click to expand!</summary>
  
  ```
  Traceback (most recent call last):
  File "/home/ben/anaconda3/envs/gluprop_test/lib/python3.8/site-packages/lyncs_utils/extensions.py", line 52, in lazy_import
    return sys.modules[name]
KeyError: 'numpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lyncs_test.py", line 1, in <module>
    import lyncs_io as io
  File "/home/ben/anaconda3/envs/gluprop_test/lib/python3.8/site-packages/lyncs_io/__init__.py", line 5, in <module>
    from .base import *
  File "/home/ben/anaconda3/envs/gluprop_test/lib/python3.8/site-packages/lyncs_io/base.py", line 13, in <module>
    from .formats import formats
  File "/home/ben/anaconda3/envs/gluprop_test/lib/python3.8/site-packages/lyncs_io/formats.py", line 10, in <module>
    from lyncs_utils import open_file
  File "/home/ben/anaconda3/envs/gluprop_test/lib/python3.8/site-packages/lyncs_utils/__init__.py", line 5, in <module>
    from .math import *
  File "/home/ben/anaconda3/envs/gluprop_test/lib/python3.8/site-packages/lyncs_utils/math.py", line 17, in <module>
    from .numpy import numpy
  File "/home/ben/anaconda3/envs/gluprop_test/lib/python3.8/site-packages/lyncs_utils/numpy.py", line 16, in <module>
    numpy = lazy_import("numpy")
  File "/home/ben/anaconda3/envs/gluprop_test/lib/python3.8/site-packages/lyncs_utils/extensions.py", line 54, in lazy_import
    spec = importlib.util.find_spec(name)
AttributeError: module 'importlib' has no attribute 'util'
  ```
</details>

**Installed versions**
Paste here the output of `lyncs_packages -v`.

> Versions listed below:

<details>
  <summary>Click to expand!</summary>
  
  ```
  cppyy==2.4.1
dataclasses==0.6
deprecated==1.2.13
filelock==3.9.0
gitpython==3.1.30
lyncs-cppyy==0.2.0
lyncs-io==0.2.3
lyncs-setuptools==0.3.1
lyncs-utils==0.4.4
numpy==1.24.1
packaging==23.0
pip==22.3.1
xmltodict==0.13.0
  ```
</details>

**Comment by sbacchio** [comment]
Hi, thank you for reporting. It seems to be an issue of your specific version of Python, not 3.8 in general or greater. I couldn't reproduce the issue directly, but as far as I can tell, it should be fixed by the new version of lyncs_utils I have pushed, namely `0.4.5`. Please update it with `pip install --upgrade lyncs_utils`, and let me know :)

**Comment by jadot-bp** [comment]
Thank you for the reply. I tested it in a 'general' way using a fresh install of 3.8 and 3.9 and neither seemed to work originally. This issue with `importlib.util` has been seen in other packages, so I had believed it to be a change in the structure of the package. Regardless, the changes made with `0.4.5` seems to have rectified this issue. Thanks!
